version: '3.7'
services:
  milter:
    build:
      context: "."
      dockerfile: "Dockerfile"
    #network_mode: host
    #restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
  postfix:
    build:
      context: "."
      dockerfile: "postfix/Dockerfile"
    ports:
      - "2525:25"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

