#Dockerfile for a milter service
FROM debian:latest
MAINTAINER João Reis joao@7lan.net

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
        python3-milter \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /
RUN pip install -r requirements.txt
COPY milter-template.py /

EXPOSE 8801/tcp
ENTRYPOINT ["/usr/bin/python3", "-u", "/milter-template.py"]
