version: '3.7'
services:
  milter:
    build:
      context: "."
      dockerfile: "Dockerfile_debian"
    network_mode: host
    #restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
